Repository Team-fast4ward/market-log, pull requests merged in 2023-02, with the labels that each got.

#12 [global scss 제품 상세페이지]
  index.html
  package-lock.json
  public/cart.svg
  public/mainLogo.svg
  public/member.svg
  public/search.svg
  public/success.svg
  src/html/productDetail.html
  src/js/page/productDetail.js
  src/scss/globals/_colors.scss
  src/scss/globals/_reset.scss
  src/scss/productsDetail.scss
Labels: enhancement

#13 Design: loading, error svg 파일 추가
  public/error.svg
  public/loading.svg
  src/scss/globals/_colors.scss
Labels: enhancement

#15 Test
  src/html/admin.html
  src/js/page/admin/admin.js
  src/scss/admin/admin.scss
Labels: enhancement

#18 로그인 기능 구현
  src/html/signup.html
  src/js/page/signup.js
Labels: enhancement

#21 Conf: package.json 불필요한 코드 삭제
  package.json
  src/js/page/productDetail.js
Labels: enhancement

#23 [공통 적용] .gitignore, index.html 변경
  .gitignore
  index.html
  src/html/productDetail.html
  src/scss/productsDetail.scss
Labels: enhancement

#29 Mapage 레이아웃 구현
  .env.development
  index.html
  package-lock.json
  src/html/mypage.html
  src/js/page/bankAccount.js
  src/scss/globals/_reset.scss
  src/scss/mypage/mypage.scss
Labels: enhancement

#30 Fix: js 파일 이름 변경
  src/html/mypage.html
  src/js/page/mypage.js
Labels: enhancement

#32 Feature/main page
  index.html
  package-lock.json
  package.json
  public/favicon.svg
  public/image/best-design.jpg
  public/image/case1.jfif
  public/image/case2.jfif
  public/image/case3.jfif
  public/image/case4.jfif
  public/image/case5.jfif
  public/image/case6.jfif
  public/image/case7.jfif
  public/image/case8.jfif
  public/image/product1.jfif
  public/image/product2.jfif
  public/image/product3.jfif
  public/image/product4.jfif
  public/image/product5.jfif
  public/image/product6.jfif
  public/image/swiper-checkcase.jpg
  public/image/swiper-keyboard.gif
  public/image/swiper-orgcase.jpg
  public/image/swiper-sale.jpg
  public/image/weekly-best0.jpg
  public/pingu.png
  src/js/main.js
  src/scss/globals/_colors.scss
  src/scss/globals/_fonts.scss
  src/scss/main.scss
Labels: enhancement

#36 Feat: 데이터 json 추가
  src/js/json.js
Labels: enhancement

#51 Feat: 계좌관리 구현 완료
  package-lock.json
  package.json
  src/html/mypage.html
  src/js/page/mypage.js
  src/scss/mypage/mypage.scss
Labels: enhancement

#53 Feature/main page
  index.html
  public/curve-line.svg
  public/purple-line.svg
  src/js/api.js
  src/js/main.js
  src/js/renderMainPage.js
  src/js/swiper.js
  src/scss/globals/_reset.scss
  src/scss/main.scss
  src/scss/swiper.scss
Labels: bug

#55 [마이페이지]주문내역페이지, 상세주문내역페이지, 개인정보수정페이지, 찜한상품페이지
  index.html
  public/calendar.svg
  public/chevronright.svg
  public/chevronrightpurple.svg
  public/exclamationmark.svg
  public/list.svg
  public/myheart.svg
  public/pagination-left.svg
  public/pagination-right.svg
  public/reload.svg
  src/html/detailedorderlist.html
  src/html/myheart.html
  src/html/mypersonalinfomodify.html
  src/html/orderhistory.html
  src/js/page/mypage/calendar.js
  src/js/page/mypage/detailHistory.js
  src/js/page/mypage/myheart.js
  src/js/page/mypage/orderhistory.js
  src/scss/mypage/detailedorderlist.scss
  src/scss/mypage/mixin.scss
  src/scss/mypage/modal.scss
  src/scss/mypage/myheart.scss
  src/scss/mypage/mypersonalinfo.scss
  src/scss/mypage/orderhistory.scss
Labels: enhancement

#56 Feat: reset.scss 및 mypage변경
  src/js/page/mypage.js
  src/scss/globals/_reset.scss
  src/scss/mypage/mypage.scss
Labels: enhancement

#57 [상세페이지 js] [장바구니 페이지 js] [결제페이지 레이아웃]
  index.html
  public/IMGproductDetail/bluetooth keyboard.jpeg
  public/IMGproductDetail/bluetooth_keyboard.jpeg
  public/success-check.svg
  src/html/cart.html
  src/html/pay.html
  src/html/productDetail.html
  src/js/page/cart/cart.js
  src/js/page/pay/pay.js
  src/js/page/productDetail/productDetail.js
  src/scss/cart/cart.scss
  src/scss/pay/pay.scss
  src/scss/productDetail/productsDetail.scss
Labels: bug, enhancement

#64 Fix: pull request 후 충돌 해결
  src/html/detailedorderlist.html
  src/js/main.js
  src/scss/main.scss
Labels: bug

#75 Feat: mypage Navigo 구현 완료
  index.html
  src/html/myheart.html
  src/html/mypage.html
  src/html/orderhistory.html
  src/js/main.js
  src/js/page/mypage.js
  src/js/page/mypage/account.js
  src/js/page/mypage/index.js
  src/js/page/mypage/myheart.js
  src/js/page/mypage/orderhistory.js
  src/scss/main.scss
  src/scss/mypage/account.scss
  src/scss/mypage/index.scss
  src/scss/mypage/myheart.scss
  src/scss/mypage/mypage.scss
  src/scss/mypage/orderhistory.scss
Labels: enhancement

#76 [주문내역페이지] orderhistory js 코드 에러들 수정
  public/calendar.svg
  public/heart.svg
  public/mainLogo.svg
  public/pagination-left.svg
  public/pagination-right.svg
  public/reload.svg
  src/html/detailedorderlist.html
  src/js/page/mypage/calendar.js
  src/js/page/mypage/orderhistory.js
  src/scss/globals/_colors.scss
  src/scss/mypage/orderhistory.scss
Labels: bug, enhancement

#96 Feat: main page 및 mypage router 구현 완료
  index.html
  src/example/index.html
  src/example/main.js
  src/example/pingu.png
  src/example/style.scss
  src/html/admin.html
  src/html/cart.html
  src/html/detailedorderlist.html
  src/html/login.html
  src/html/myheart.html
  src/html/mypage.html
  src/html/mypersonalinfomodify.html
  src/html/orderhistory.html
  src/html/pay.html
  src/html/productDetail.html
  src/html/signup.html
  src/js/api.js
  src/js/json.js
  src/js/main.js
  src/js/page/cart/cart.js
  src/js/page/login.js
  src/js/page/mypage.js
  src/js/page/mypage/account.js
  src/js/page/mypage/detailHistory.js
  src/js/page/mypage/myheart.js
  src/js/page/mypage/orderhistory.js
  src/js/page/productDetail/productDetail.js
  src/js/page/signup.js
  src/js/renderMainPage.js
  src/js/swiper.js
  src/scss/globals/_colors.scss
  src/scss/login/login.scss
  src/scss/main.scss
  src/scss/mypage/account.scss
  src/scss/mypage/detailedorderlist.scss
  src/scss/mypage/index.scss
  src/scss/mypage/mixin.scss
  src/scss/mypage/modal.scss
  src/scss/mypage/myheart.scss
  src/scss/mypage/mypage.scss
  src/scss/mypage/mypersonalinfo.scss
  src/scss/mypage/orderhistory.scss
  src/scss/pay/pay.scss
  src/scss/signup/signup.scss
  src/scss/swiper.scss
Labels: enhancement

#99 2월 15일 22시 merge 완료
  index.html
  src/scss/mypage/account.scss
  src/scss/mypage/detailedorderlist.scss
Labels: enhancement

#111 Feat: 불필요한 파일 삭제 및 회원가입 유효성검사 추가
  .env.development
  index.html
  src/js/main.js
  src/js/page/cart/cart.js
  src/js/page/login.js
  src/js/page/mypage.js
  src/js/page/mypage/account.js
  src/js/page/productDetail/productDetail.js
  src/js/page/signup.js
  src/js/testChanYoung.js
  src/js/testJaeha.js
  src/scss/cart/cart.scss
  src/scss/category/category.scss
  src/scss/mypage/account.scss
  src/scss/pay/pay.scss
  src/scss/productDetail/productsDetail.scss
  src/scss/searchPage/searchPage.scss
  src/scss/signup/signup.scss
Labels: enhancement

#115 Feat: 관리자 로그인 및 pw입력 후 엔터로 로그인 구현
  src/js/page/login.js
Labels: enhancement

#118 Feat: router에 handle함수 통일 및 기타 기능 구현
  src/js/main.js
  src/js/page/login.js
  src/js/page/mypage.js
  src/js/page/mypage/account.js
  src/js/page/mypage/detailHistory.js
  src/js/page/mypage/editPersonaInfo.js
  src/js/page/mypage/orderhistory.js
  src/js/page/paymentPage/paymentPage.js
  src/js/page/signup.js
  src/js/page/wishListPage/wishListPage.js
Labels: enhancement

#129 [2/22 16:46] PR
  index.html
  public/search.gif
  src/js/page/cartPage/cartPage.js
  src/js/page/mainPage/mainPage.js
Labels: enhancement

#130 [2/22 17:01] PR
  index.html
  public/spinner.svg
  src/js/page/admin/dashboard.js
  src/js/page/admin/format.js
  src/js/page/admin/order.js
  src/js/page/admin/product.js
  src/js/page/admin/productAdd.js
  src/js/page/admin/renderDetail.js
  src/js/page/admin/renderTemplate.js
  src/js/utils/loading.js
  src/scss/admin/order.scss
  src/scss/admin/product.scss
  src/scss/mypage/mypage.scss
Labels: enhancement

#131 [2/22 17:19] PR
  index.html
  public/outlink.png
  src/js/api.js
  src/js/importIMGFiles.js
  src/js/main.js
  src/js/page/cartPage/cartPage.js
  src/js/page/detailOrderHistoryPage/detailOrderHistory.js
  src/js/page/login.js
  src/js/page/mypage.js
  src/js/page/mypage/account.js
  src/js/page/mypage/editPersonaInfo.js
  src/js/page/mypage/editPersonalInfo.js
  src/js/page/mypage/orderhistory.js
  src/js/page/signup.js
  src/js/page/wishListPage/wishListPage.js
  src/scss/main.scss
  src/scss/mypage/editPersonalInfo.scss
  src/scss/mypage/mypage.scss
  src/scss/mypage/mypersonalinfo.scss
Labels: enhancement

#132 [2/22 18:59] PR
  src/js/api.js
  src/js/page/mypage/editPersonalInfo.js
Labels: enhancement

#134 [관리자 페이지] Type 지정
  src/ts/api.ts
  src/ts/interface/cy.ts
  src/ts/interface/index.ts
  src/ts/main.ts
  src/ts/page/admin/dashboard.ts
  src/ts/page/admin/order.ts
  src/ts/page/admin/orderDetail.ts
  src/ts/page/admin/product.ts
  src/ts/page/admin/productAdd.ts
  src/ts/page/admin/productDetail.ts
  src/ts/page/admin/productEdit.ts
  src/ts/page/admin/renderDetail.ts
  src/ts/page/admin/renderTemplate.ts
  src/ts/utils/date.ts
  src/ts/utils/format.ts
Labels: enhancement

#135 [2/24 14:06] PR
  src/ts/api.ts
  src/ts/interface/index.ts
  src/ts/page/mypage.ts
  src/ts/page/mypage/account.ts
  src/ts/page/signup.ts
Labels: enhancement

#137 [2/24 14:46] PR
  src/ts/api.ts
  src/ts/interface/index.ts
  src/ts/page/admin/dashboard.ts
  src/ts/page/admin/order.ts
  src/ts/page/admin/product.ts
  src/ts/page/admin/renderDetail.ts
Labels: enhancement

#138 [2/24 15:15] 김영은 PR
  src/ts/api.ts
  src/ts/interface/index.ts
  src/ts/page/errorPage/errorPage.ts
  src/ts/page/login.ts
  src/ts/page/mypage/editPersonalInfo.ts
Labels: bug, enhancement

#139 [2/24 15:15] PR
  src/ts/main.ts
  src/ts/page/admin/dashboard.ts
  src/ts/page/admin/order.ts
  src/ts/page/admin/orderDetail.ts
  src/ts/page/admin/product.ts
  src/ts/page/admin/productAdd.ts
  src/ts/page/admin/productDetail.ts
  src/ts/page/admin/productEdit.ts
Labels: bug, documentation

#142 [2/26 18:46] PR
  src/ts/page/mypage/account.ts
  src/ts/page/mypage/orderhistory.ts
  src/ts/page/signup.ts
Labels: bug
